[settings]
learning_rate = 0.0001
batch_size = 64
iterations = 10

[[layer]]
type = "lowrank"
dim_in = 784
dim_out = 128
activation = "relu"
rank = 20

[[layer]]
type = "lowrank"
dim_in = 128
dim_out = 64
activation = "relu"
rank = 20

[[layer]]
type = "dense"
dim_in = 64
dim_out = 10
activation = "linear"